### ISSUE TITLE
[Feature Request] hide key bindings

### ISSUE THREAD

**Issue by BredyAK** [blay09/DefaultKeyConfig#82]
hi there, i'm a mod pack maker, and currently i'm looking for a mod which could hide some key bindings that i don't want players to change, so i find this mod, it is nice, which could make default key bindings but won't override player's key settings. but currently it doesn't provide a function which could let our mod pack makers hiding specific key bindings.

for example, there is a a mod called `Shoulder Surfing`, it provides a cool function of player's camera, i don't want players change my settings by using the key binds that the mod provided.
![image](https://github.com/user-attachments/assets/e6f66fc3-e62d-4336-953f-a1807ca310d5)

and i also want to request that, if ALL keys from a category are hiden, then the category title should be hiden too.
![image](https://github.com/user-attachments/assets/17b6ee22-734c-4430-9e98-6924920c0b09)

there is already a mod that provides the feature i request: [https://github.com/Nova-Committee/InvisibleKeyBinding/tree/forge-dev](https://github.com/Nova-Committee/InvisibleKeyBinding/tree/forge-dev), but it's a private project (for personal usage) that isn't released to CurseForge of Modrinth, it's such a pity.

i like the private mod above because it supports hiding key category& single key, and it provides a config file like this:
```toml

#InvisibleKeybinding Settings
[general]
	#Keybindings that should be invisible in the controls screen
	invisibleKeybindings = ["Quest Log", "Scene reset", "Scene1 start/pause", "Scene2 start/pause", "Scene3 start/pause", "key.presencefootsteps.settings", "key.advancements", "Toggle perspective"]
	#Keybinding categories that should be invisible in the controls screen
	invisibleCategories = ["asteorbar.key.category", "keygroup.commandkeys.main", "key.fbp.category", "Firstperson", "modmenu.nameTranslation.jade", "jm.common.hotkeys_keybinding_category", "jm.common.hotkeys_keybinding_fullscreen_category", "Modern UI", "physicsmod.keybinding.category", "key.categories.trashslot", "key.modernfix"]
```

it's such powerful because it could hide a whole category by its localization key.

you can refer to the implementation method of this mod. i believe this will be a simple but powerful feature!

Thank you for bringing us this nice mod!
